Play travis
Otus-DevOps-2018-09/belogrud_infra pull request #1
Opened 2018-10-16 09:05 UTC by belogrud

Домашнее задание к уроку 04: "Локальное окружение инженера. ChatOps и визуализация рабочих процессов. Командная работа с Git. Работа в GitHub.".

Оформление комментария согласно рекомендациям из "Инструкция._Работа_с_интерфеи_сом_в_Github-8278-0e785a.pdf", стр.5.

Работа выполнялась по методичке “Практика._Локальное_окружение_инженера._Командное_взаимодеи_ствие_и_управление_рабочими_процессами-8278-f2946e.pdf”.

Что сделано.
*. Произведены манипуляции в Slack. В нём создан отдельный канал имени меня. К каналу подключен Git репозиторий Otus-DevOps-2018-09/belogrud_infra. К каналу подключен сервис Travis CI.
*. Создана ветка play-travis в репозитории Otus-DevOps-2018-09/belogrud_infra.
*. В ветку play-travis добавлены несколько файлов.
*. Создан этот pull request.

Как проверить.
Проверить существование файлов в репозитории.
•.github/PULL_REQUEST_TEMPLATE.md
•.travis.yml
•play-travis/test.py

Замечания.
*. Куда ставить правильные label'ы - не понял.
*. Начиная со страницы 25 методики - что делать дальше - не понял. Написал об этом в чате Otus “ДЗ: Настройка локального окружения и практика ChatOps.”. Но этот чат, похоже, редко читают и реагируют на сообщения.
*. Как это всё работает понял только в общем и смутно. Методички по выполнению домашних работ слабоваты - поверхностные - вынуждаю задаваться уймой не объяснённых вопросов - тратить на это своё и преподавателей время. Слабые методички заметно снижают качество обучения. К сожалению, трудно выделять время на поиск ответов и разрешение вопросов, возникающим по ходу выполнения домашних заданий. Времени сильно не хватает так-как обучение практически всегда совмещено с основной работой и выживанием в условиях российского политико-экономического режима.

2018-10-16 11:28 UTC, hostberg requested changes
К соджалению, не могу принять задание. 

- Не пройдены проверки Travis CI (.travis.yml должен быть в корне репо);
- Не могу проверить интеграцию ( не вижу slack-канал в спейсе devops-team-otus.slack.com);
- При создании PR справа есть надпись Labels c ⚙.

Если есть какие-то конкретные вопросы, с удовольствием постараемся ответить в Slack'е.

2018-10-16 14:09 UTC, belogrud commented
1. Файл .travis.yml я переместил в корень репозитория. Это в последнем коммите. Теперь нужно закрыть этот Pull Request кнопкой "Close and comment"? И сделать новый Pull Request? Или как?

2. Что нужно сделать, чтобы вы увидели slack-канал в спейсе devops-team-otus.slack.com?
Какие-то инвайты разослать @vitkhab, @mmikhaylov? Где и как это делается?

2018-10-16 14:22 UTC, hostberg commented
1. Сначала нужно сделать так, чтобы прошли все проверки Travis CI:

- Travis CI - Branch Action required after 39s — Build Errored;
- Travis CI - Pull Request Action required after 45s — Build Errored.

2. Отправьте инвайты @vitkhab, @mmikhaylov. При создании канала с первых строчка есть `Invite others to this channel`.

2018-10-16 16:51 UTC, belogrud commented
1. Не понял, как это работает: "Сначала нужно сделать так, чтобы прошли все проверки Travis CI:".
Это так делается:
Внёс изменения в файл play-travis/test.py. Закомитил и запушил.
Теперь ждать или куда-то нажать нужно?

[s.belogrud@TCS4357]# git --no-pager log -n 1 -p play-travis/test.py
commit b7e54b716c87bfc19deadd4c65d4f9eff40dd687
Author: Your Name <you@example.com>
Date:   Tue Oct 16 19:47:01 2018 +0300

    Was changed one digit inside a file test.py. It's to pass thrue test correctly.

diff --git a/play-travis/test.py b/play-travis/test.py
index 8fff0ff..8381bad 100644
--- a/play-travis/test.py
+++ b/play-travis/test.py
@@ -3,7 +3,7 @@ import unittest
 class NumbersTest(unittest.TestCase):

     def test_equal(self):
-        self.assertEqual(1 + 1, 1)
+        self.assertEqual(1 + 1, 2)

 if __name__ == '__main__':
-    unittest.main()
\ No newline at end of file
+    unittest.main()
[s.belogrud@TCS4357]#


2. Создал канал в Slack: sergey_belogrud. Выслал инвайты.
joined #sergey_belogrud by invitation from Sergey Belogrud, along with Vitaly Khabarov.
Подключил канал к Git репозиторию.
Сделал два тестовых комита, чтобы увидеть, что информация о комитах появляется в канале.

2018-10-16 16:53 UTC, belogrud commented
Чтобы код в этот комментарий вставлять без его форматирования нужно использовать вот эти символы: <>?

`
code body
`

2018-10-16 20:06 UTC, hostberg commented
Насколько я вижу, бот Travis CI не отписал о билдах в slack-канал `#sergey_belogrud`, значит интеграция Slack и Travis CI настроена некорректно. Для обсуждения рекомендую использовать основной slack-канал группы, а не коментарии к pull request'у.

2018-10-17 08:34 UTC, belogrud commented
Написал вопрос в Slack: DevOps-2018-09 в #group-2018-09.

2018-10-17 09:39 UTC, hostberg approved these changes

2018-10-17 09:39 UTC, hostberg commented
Работа принята. 👍

2018-10-17 09:48 UTC, merged