Ansible 2
Otus-DevOps-2018-09/belogrud_infra pull request #8
Opened 2018-11-22 16:45 UTC by belogrud

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2018-12-15 19:19 UTC, mrgreyves requested changes
Здравствуйте! Проверил ваше дз. К сожалению есть замечания: в файла оставил текстовые замечания. Так же прошу Вас отредактировать пулл реквест и ридми файл. Спасибо!)

2018-12-15 19:19 UTC, mrgreyves commented on ansible/app.yml
> +- name: Configure App
не хватает 3х тире

2018-12-15 19:19 UTC, mrgreyves commented on ansible/deploy.yml
> +- name: Deploy App
не хватает 3х тире

2018-12-17 16:58 UTC, belogrud commented on ansible/app.yml
> +- name: Configure App
Добавил три тире - всё сломалось.

2018-12-17 16:59 UTC, belogrud commented on ansible/deploy.yml
> +- name: Deploy App
Валидация перестала проходить.

2018-12-17 17:05 UTC, belogrud commented
Разломалось... блин.

2018-12-17 18:38 UTC, mrgreyves commented
Здравствуйте!) Ничего страшного, есть у тестов особенность периодически ломаться.)

2018-12-17 18:44 UTC, mrgreyves commented
ЗЫ: заполните пожалуйста корректно пуллреквест)

2018-12-18 13:48 UTC, belogrud commented
Могли бы уточнить: "ЗЫ: заполните пожалуйста корректно пуллреквест)".
Это про что и где?
Что куда вписать, выписать?
Где, что не хватает?
Куда смотреть?

2018-12-18 13:58 UTC, mrgreyves commented
Здравствуйте! http://prntscr.com/lwiyhq  скриншотик) Имелось ввиду описание пулреквеста. Оно должно быть более информативным!)

2018-12-18 14:50 UTC, belogrud commented
Заполнил форму.
Я-то в README.md это пишу в основном.

2018-12-26 17:42 UTC, mrgreyves approved these changes
Здравствуйте!) Спасибо, дз принимаю!)

2025-03-23 02:51 UTC, closed without merging